# Generated by Django 5.0.2 on 2024-04-13 16:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0002_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('hora', models.TimeField()),
                ('cantidad_boletos', models.PositiveIntegerField(default=0)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud1.pelicula')),
            ],
        ),
    ]
